# This file configures your Netlify build and development environment

[build]
  functions = "netlify/functions"
  publish = "dist" 

[functions."ask-assistant"]
  # Increase the timeout for all functions to 25 seconds
  timeout = 25

# This sets up the local development server (netlify dev)
[dev]
  # The command to start your frontend app
  command = "npm run dev"
  # The port for the frontend server
  port = 5171 # Default Vite port
  # The port for the functions server
  functionsPort = 8888

# Redirect rule to make calling the function easier from the frontend
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200