# This file configures your Netlify build and development environment

[build]
  functions = "netlify/functions"
  publish = "dist"

# This block is for your local "netlify dev" command
[dev]
  command = "npm run dev"
  port = 5171
  functionsPort = 8888

# This redirect sends API calls to your function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# This "catch-all" redirect is crucial for Single-Page Apps.
# It ensures that refreshing the page always works correctly.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200